apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: greek-sculptor-api
spec:
# recommenders field can be unset when using the default recommender.
# When using an alternative recommender, the alternative recommender’s name
# can be specified as the following in a list.
# recommenders:
# — name: ‘alternative’
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: greek-sculptor-api-chart
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: 200m
        memory: 150Mi
      maxAllowed:
        cpu: 1
        memory: 300Mi
      controlledResources: ["cpu", "memory"]